# Generated by Django 4.2.7 on 2024-10-07 06:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='error_log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('method', models.TextField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('error_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'error_log',
            },
        ),
        migrations.CreateModel(
            name='MenuMaster',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_name', models.CharField(blank=True, max_length=50, null=True)),
                ('menu_action', models.CharField(blank=True, max_length=50, null=True)),
                ('menu_is_parent', models.BooleanField(blank=True, null=True)),
                ('menu_parent_id', models.IntegerField(blank=True, null=True)),
                ('menu_order', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('is_sub_menu', models.BooleanField(blank=True, null=True)),
                ('sub_menu', models.IntegerField(blank=True, null=True)),
                ('is_sub_menu2', models.BooleanField(blank=True, null=True)),
                ('sub_menu2', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
                ('menu_icon', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'menu_master',
            },
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_text', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'otp_verification',
            },
        ),
        migrations.CreateModel(
            name='password_storage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('passwordText', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'password_storage',
            },
        ),
        migrations.CreateModel(
            name='RoleMenuMaster',
            fields=[
                ('role_menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_id', models.CharField(blank=True, max_length=50, null=True)),
                ('menu_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'role_menu_master',
            },
        ),
        migrations.CreateModel(
            name='user_dept_services',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('department_id', models.BigIntegerField(blank=True, null=True)),
                ('service_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_dept_services',
            },
        ),
        migrations.CreateModel(
            name='UserMenuDetails',
            fields=[
                ('user_menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('menu_id', models.IntegerField(blank=True, null=True)),
                ('role_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_menu_details',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('first_time_login', models.IntegerField(default=1)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('device_token', models.CharField(blank=True, max_length=255, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
