# Generated by Django 4.2.7 on 2024-10-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_remove_otpverification_user_otpverification_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='superior_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
