# Generated by Django 6.0.1 on 2026-02-03 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_alter_customuser_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('user_type', models.CharField(blank=True, choices=[('admin', 'Admin'), ('citizen', 'Citizen')], max_length=20, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent_hash', models.CharField(blank=True, max_length=256, null=True)),
                ('stored_user_agent_hash', models.CharField(blank=True, max_length=256, null=True)),
                ('stored_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('action', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbl_session_activity_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
