# Generated by Django 6.0.1 on 2026-02-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0008_sessionactivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionactivitylog',
            name='stored_user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionactivitylog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
