# Generated by Django 6.0.1 on 2026-07-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0009_sessionactivitylog_stored_user_agent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='passwordChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('old_password', models.CharField(blank=True, max_length=256, null=True)),
                ('new_password', models.CharField(blank=True, max_length=256, null=True)),
                ('changed_by', models.CharField(blank=True, max_length=256, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbl_password_change_log',
                'ordering': ['-updated_at'],
            },
        ),
    ]
