# Generated by Django 4.2.7 on 2024-09-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0010_alter_password_storage_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_dept_services',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('department_id', models.BigIntegerField(blank=True, null=True)),
                ('service_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_dept_services',
            },
        ),
        migrations.DeleteModel(
            name='AssignedCompany',
        ),
        migrations.RemoveField(
            model_name='filestest',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='filestest',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='user_role_map',
        ),
        migrations.DeleteModel(
            name='FilesTest',
        ),
    ]
