# Generated by Django 4.2.23 on 2026-06-10 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='application_form',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request_no', models.TextField(blank=True, null=True)),
                ('status_id', models.IntegerField(blank=True, null=True)),
                ('village_name', models.TextField(blank=True, null=True)),
                ('bp_fire_no', models.TextField(blank=True, null=True)),
                ('survey_no', models.TextField(blank=True, null=True)),
                ('plot_no', models.TextField(blank=True, null=True)),
                ('architect_name', models.TextField(blank=True, null=True)),
                ('builder_name', models.TextField(blank=True, null=True)),
                ('plot_area', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('submission_month', models.CharField(blank=True, max_length=10, null=True)),
                ('submission_type', models.CharField(blank=True, max_length=20, null=True)),
                ('is_draft', models.IntegerField(default=1)),
                ('comments', models.TextField(blank=True, null=True)),
                ('approved_remark', models.TextField(blank=True, null=True)),
                ('rejected_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'application_form',
            },
        ),
        migrations.CreateModel(
            name='citizen_document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('file_name', models.TextField(blank=True, null=True)),
                ('filepath', models.CharField(blank=True, max_length=1000, null=True)),
                ('doc_id', models.IntegerField(blank=True, null=True)),
                ('application_id', models.IntegerField(blank=True, null=True)),
                ('correct_mark', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'citizen_document',
            },
        ),
        migrations.CreateModel(
            name='internal_doc_master',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_name', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'internal_doc_master',
            },
        ),
        migrations.CreateModel(
            name='workflow_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request_no', models.TextField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('status_id', models.IntegerField(blank=True, null=True)),
                ('form_user_id', models.IntegerField(blank=True, null=True)),
                ('form_id', models.IntegerField(blank=True, null=True)),
                ('send_forward', models.TextField(blank=True, null=True)),
                ('forward', models.TextField(blank=True, null=True)),
                ('sendback', models.TextField(blank=True, null=True)),
                ('rollback', models.TextField(blank=True, null=True)),
                ('pre_statusid', models.TextField(blank=True, null=True)),
                ('pre_user', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'workflow_details',
            },
        ),
        migrations.CreateModel(
            name='workflow_history',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('workflow_id', models.IntegerField(blank=True, null=True)),
                ('request_no', models.TextField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('status_id', models.IntegerField(blank=True, null=True)),
                ('form_user_id', models.IntegerField(blank=True, null=True)),
                ('form_id', models.IntegerField(blank=True, null=True)),
                ('send_forward', models.TextField(blank=True, null=True)),
                ('forward', models.TextField(blank=True, null=True)),
                ('sendback', models.TextField(blank=True, null=True)),
                ('rollback', models.TextField(blank=True, null=True)),
                ('pre_statusid', models.TextField(blank=True, null=True)),
                ('pre_user', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'workflow_history',
            },
        ),
        migrations.CreateModel(
            name='internal_user_document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.TextField(blank=True, null=True)),
                ('file_path', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_intdoc_aqi', to='aqi.workflow_details')),
            ],
            options={
                'db_table': 'internal_user_document',
            },
        ),
        migrations.CreateModel(
            name='internal_user_comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_intcom_aqi', to='aqi.workflow_details')),
            ],
            options={
                'db_table': 'internal_user_comments',
            },
        ),
    ]
