# Generated by Django 4.2.23 on 2026-06-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application_form',
            name='issued_certificate_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application_form',
            name='refused_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
