# Generated by Django 4.2.23 on 2026-06-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqi', '0002_application_form_issued_certificate_remark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application_form',
            name='monthly_aqi_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application_form',
            name='monthly_aqi_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application_form',
            name='monthly_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application_form',
            name='parent_application_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
