# Generated by Django 4.2.7 on 2025-01-31 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApproval', '0002_alter_application_form_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application_form',
            old_name='address',
            new_name='cin',
        ),
        migrations.RenameField(
            model_name='application_form',
            old_name='applicant_type',
            new_name='contact_person_name',
        ),
        migrations.RenameField(
            model_name='application_form',
            old_name='committee_approval',
            new_name='factory_location',
        ),
        migrations.RenameField(
            model_name='application_form',
            old_name='committee_refusal',
            new_name='factory_name',
        ),
        migrations.RenameField(
            model_name='application_form',
            old_name='name_of_applicant',
            new_name='gstin',
        ),
        migrations.RenameField(
            model_name='application_form',
            old_name='plot_no',
            new_name='license_no',
        ),
        migrations.RenameField(
            model_name='application_form',
            old_name='reason_for_cutting_trees',
            new_name='mobile_no',
        ),
        migrations.RenameField(
            model_name='application_form',
            old_name='survey_no',
            new_name='pan_no',
        ),
        migrations.RemoveField(
            model_name='application_form',
            name='total_trees_to_trim',
        ),
        migrations.AddField(
            model_name='application_form',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='application_form',
            name='product_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
