# Generated by Django 5.0.9 on 2025-12-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApproval', '0003_rename_address_application_form_cin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application_form',
            name='product_type_service',
            field=models.TextField(blank=True, null=True),
        ),
    ]
