# Generated by Django 6.0.1 on 2026-03-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApproval', '0004_application_form_product_type_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='application_form',
            name='declaration',
            field=models.BooleanField(default=False),
        ),
    ]
