# Generated by Django 4.2.7 on 2024-11-14 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='document_master',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_name', models.TextField(blank=True, null=True)),
                ('doc_subpath', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
                ('is_active', models.IntegerField(default=1)),
                ('mandatory', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'document_master',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'logs',
            },
        ),
        migrations.CreateModel(
            name='nodal_master',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nodal_office_location', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nodal_master',
            },
        ),
        migrations.CreateModel(
            name='status_master',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.TextField(blank=True, null=True)),
                ('status_type', models.TextField(blank=True, null=True)),
                ('is_active', models.IntegerField(default=1)),
                ('level', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'status_master',
            },
        ),
        migrations.CreateModel(
            name='service_matrix',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('role_id', models.TextField(blank=True, null=True)),
                ('action', models.TextField(blank=True, null=True)),
                ('reference', models.TextField(blank=True, null=True)),
                ('model', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
                ('ser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ser_id_F', to='Account.service_master')),
            ],
            options={
                'db_table': 'service_matrix',
            },
        ),
        migrations.CreateModel(
            name='parameter_master',
            fields=[
                ('parameter_id', models.AutoField(primary_key=True, serialize=False)),
                ('parameter_name', models.TextField(blank=True, null=True)),
                ('parameter_value', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameter_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameter_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'parameter_master',
            },
        ),
        migrations.CreateModel(
            name='application_search',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('href', models.TextField(blank=True, null=True)),
                ('menu_id', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_search_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_search_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'application_search',
            },
        ),
    ]
