# Generated by Django 4.2.7 on 2024-11-16 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_matrix',
            name='ser',
        ),
    ]
