# Generated by Django 4.2.7 on 2024-10-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status_master',
            name='status_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
