# Generated by Django 4.2.7 on 2024-10-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0002_status_master_status_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='smslog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('user_id', models.CharField(max_length=50)),
                ('content', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('unique_id', models.CharField(blank=True, max_length=50, null=True)),
                ('content_type', models.CharField(max_length=50)),
                ('response_status', models.CharField(max_length=20)),
                ('is_successful', models.BooleanField(default=False)),
                ('response_url', models.TextField(blank=True, null=True)),
                ('status_description', models.TextField(blank=True, null=True)),
                ('template_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'smslog',
            },
        ),
        migrations.CreateModel(
            name='smstext',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('template_name', models.TextField(blank=True, null=True)),
                ('template_id', models.TextField(blank=True, null=True)),
                ('sms_id_number', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'smstext',
            },
        ),
    ]
