# Generated by Django 4.2.7 on 2024-11-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0002_remove_service_matrix_ser'),
    ]

    operations = [
        migrations.CreateModel(
            name='status_color',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'status_color',
            },
        ),
    ]
