# Generated by Django 4.2.7 on 2024-11-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0003_status_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='status_master',
            name='status_color',
            field=models.TextField(blank=True, null=True),
        ),
    ]
