# Generated by Django 4.2.7 on 2025-01-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0004_status_master_status_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_matrix',
            name='timeline',
            field=models.TextField(blank=True, null=True),
        ),
    ]
