# Generated by Django 4.2.7 on 2025-01-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0005_service_matrix_timeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='document_master',
            name='doc_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
