# Generated by Django 4.2.7 on 2024-10-21 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0006_application_form_approved_remark_and_more'),
        ('Masters', '0006_internal_user_document_file_path'),
    ]

    operations = [
    ]
