# Generated by Django 4.2.7 on 2024-10-21 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0007_merge_20241021_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='internal_user_comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_intcom_F', to='Masters.workflow_details')),
            ],
            options={
                'db_table': 'internal_user_comments',
            },
        ),
    ]
