# Generated by Django 4.2.7 on 2025-02-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0007_api_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='api_data',
            name='form_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_data',
            name='form_user_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api_data',
            name='workflow_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
