# Generated by Django 4.2.7 on 2024-10-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0008_internal_user_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service_matrix',
            old_name='href',
            new_name='model',
        ),
        migrations.AddField(
            model_name='service_matrix',
            name='reference',
            field=models.TextField(blank=True, null=True),
        ),
    ]
