# Generated by Django 6.0.1 on 2026-03-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0009_document_master_order_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_matrix',
            name='service_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
