# Generated by Django 6.0.1 on 2026-03-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0010_service_matrix_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='status_master',
            name='service_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
