# Generated by Django 4.2.7 on 2024-10-24 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0011_citizen_document_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen_document',
            name='document',
            field=models.ForeignKey(blank=True, db_column='doc_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citizen_documents_f', to='Masters.document_master'),
        ),
    ]
