# Generated by Django 4.2.7 on 2024-10-24 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0011_citizen_document_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizen_document',
            name='incorrect_mark',
        ),
    ]
