# Generated by Django 4.2.7 on 2024-10-25 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0012_alter_citizen_document_document'),
        ('Masters', '0012_remove_citizen_document_incorrect_mark'),
    ]

    operations = [
    ]
