# Generated by Django 4.2.7 on 2024-10-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0013_merge_20241025_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow_details',
            name='forward',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflow_details',
            name='previous_user',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflow_details',
            name='send_forward',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflow_history',
            name='forward',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflow_history',
            name='previous_user',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflow_history',
            name='send_forward',
            field=models.TextField(blank=True, null=True),
        ),
    ]
