# Generated by Django 4.2.7 on 2024-10-28 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0015_status_master_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflow_details',
            old_name='previous_user',
            new_name='pre_statusid',
        ),
        migrations.RenameField(
            model_name='workflow_history',
            old_name='previous_user',
            new_name='pre_statusid',
        ),
        migrations.AddField(
            model_name='workflow_details',
            name='pre_user',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflow_history',
            name='pre_user',
            field=models.TextField(blank=True, null=True),
        ),
    ]
