# Generated by Django 4.2.7 on 2024-11-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0017_workflow_details_sendback_workflow_history_sendback'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow_details',
            name='rollback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflow_history',
            name='rollback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
