# Generated by Django 4.2.7 on 2024-11-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0019_application_form_tc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_matrix',
            name='role',
        ),
        migrations.AddField(
            model_name='service_matrix',
            name='role_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
