# Generated by Django 4.2.7 on 2024-09-26 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Masters', '0019_remove_application_search_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentMaster',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'department_master',
            },
        ),
        migrations.CreateModel(
            name='DocumentMaster',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_name', models.CharField(blank=True, max_length=255, null=True)),
                ('doc_path', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'document_master',
            },
        ),
        migrations.CreateModel(
            name='LevelActionMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(blank=True, max_length=100, null=True)),
                ('next_action', models.CharField(blank=True, max_length=100, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'level_action_mapping',
            },
        ),
        migrations.CreateModel(
            name='NodalMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nodal_office_location', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'nodal_master',
            },
        ),
        migrations.CreateModel(
            name='ServiceMaster',
            fields=[
                ('ser_id', models.AutoField(primary_key=True, serialize=False)),
                ('ser_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('dept_id_id', models.ForeignKey(blank=True, db_column='dept_id_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dept_id_F', to='Masters.departmentmaster')),
            ],
            options={
                'db_table': 'service_master',
            },
        ),
        migrations.CreateModel(
            name='StatusMaster',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'status_master',
            },
        ),
        migrations.CreateModel(
            name='WorkflowDetail',
            fields=[
                ('request_no', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('action', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('user_id_id', models.ForeignKey(blank=True, db_column='user_id_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_id_F', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workflow_details',
            },
        ),
        migrations.CreateModel(
            name='ServiceMatrix',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('role_name', models.CharField(blank=True, max_length=100, null=True)),
                ('action', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('ser_id_id', models.ForeignKey(blank=True, db_column='ser_id_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ser_id_id_F', to='Masters.servicemaster')),
            ],
            options={
                'db_table': 'service_matrix',
            },
        ),
        migrations.CreateModel(
            name='InternalUserDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('request_no_id', models.ForeignKey(blank=True, db_column='request_no_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_no_F', to='Masters.workflowdetail')),
            ],
            options={
                'db_table': 'internal_user_document',
            },
        ),
        migrations.CreateModel(
            name='CitizenDocument',
            fields=[
                ('userdocumentid', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('doc_id_id', models.ForeignKey(blank=True, db_column='doc_id_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_id_id_F', to='Masters.documentmaster')),
            ],
            options={
                'db_table': 'citizen_document',
            },
        ),
    ]
