# Generated by Django 4.2.7 on 2024-09-26 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0020_departmentmaster_documentmaster_levelactionmapping_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sc_roster',
        ),
    ]
