# Generated by Django 4.2.7 on 2024-09-26 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0021_delete_sc_roster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_master',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='company_master',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='file_checksum',
            name='company',
        ),
        migrations.RemoveField(
            model_name='file_checksum',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='file_errorlog',
            name='checksum',
        ),
        migrations.RemoveField(
            model_name='file_errorlog',
            name='company',
        ),
        migrations.RemoveField(
            model_name='file_errorlog',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='sc_employee_master',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='sc_employee_master',
            name='employment_status',
        ),
        migrations.RemoveField(
            model_name='sc_employee_master',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='site_master',
            name='company',
        ),
        migrations.RemoveField(
            model_name='site_master',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='site_master',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='application_search',
        ),
        migrations.DeleteModel(
            name='company_master',
        ),
        migrations.DeleteModel(
            name='file_checksum',
        ),
        migrations.DeleteModel(
            name='file_errorlog',
        ),
        migrations.DeleteModel(
            name='sc_employee_master',
        ),
        migrations.DeleteModel(
            name='site_master',
        ),
    ]
