# Generated by Django 4.2.7 on 2024-11-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0021_service_master_redirect_to_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='application_form_tc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.TextField(blank=True, null=True)),
                ('applicant_type', models.TextField(blank=True, null=True)),
                ('name_of_applicant', models.TextField(blank=True, null=True)),
                ('plot_no', models.TextField(blank=True, null=True)),
                ('survey_no', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('total_existing_no_of_trees', models.IntegerField(blank=True, null=True)),
                ('proposed_no_of_trees_to_cut_or_transplant', models.IntegerField(blank=True, null=True)),
                ('balance_no_of_trees_to_retain', models.IntegerField(blank=True, null=True)),
                ('reason_for_cutting_trees', models.TextField(blank=True, null=True)),
                ('request_no', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('approved_remark', models.TextField(blank=True, null=True)),
                ('issued_certificate_remark', models.TextField(blank=True, null=True)),
                ('refused_reason', models.TextField(blank=True, null=True)),
                ('rejected_reason', models.TextField(blank=True, null=True)),
                ('committee_refusal', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'application_form_tc',
            },
        ),
        migrations.CreateModel(
            name='citizen_document_tc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('file_name', models.TextField(blank=True, null=True)),
                ('filepath', models.CharField(blank=True, max_length=1000, null=True)),
                ('document', models.TextField(blank=True, null=True)),
                ('correct_mark', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
                ('application_id', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'citizen_document_tc',
            },
        ),
    ]
