# Generated by Django 4.2.7 on 2024-11-12 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0022_application_form_tc_citizen_document_tc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen_document_tc',
            name='application_id',
            field=models.ForeignKey(blank=True, db_column='application_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_id_Ftc', to='Masters.application_form_tc'),
        ),
        migrations.AlterField(
            model_name='citizen_document_tc',
            name='document',
            field=models.ForeignKey(blank=True, db_column='doc_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citizen_documents_ftc', to='Masters.document_master'),
        ),
    ]
