# Generated by Django 4.2.7 on 2024-10-04 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0023_application_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenDocumentFilePath',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('filepath', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'citizen_document',
            },
        ),
        migrations.CreateModel(
            name='FormDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_no', models.CharField(blank=True, max_length=100, null=True)),
                ('name_of_premises', models.CharField(blank=True, max_length=255, null=True)),
                ('plot_no', models.CharField(blank=True, max_length=100, null=True)),
                ('sector_no', models.CharField(blank=True, max_length=100, null=True)),
                ('node', models.CharField(blank=True, max_length=100, null=True)),
                ('name_of_owner', models.CharField(blank=True, max_length=255, null=True)),
                ('address_of_owner', models.TextField(blank=True, null=True)),
                ('name_of_plumber', models.CharField(blank=True, max_length=255, null=True)),
                ('license_no_of_plumber', models.CharField(blank=True, max_length=100, null=True)),
                ('address_of_plumber', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('plot_size', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_flats', models.IntegerField(blank=True, null=True)),
                ('no_of_shops', models.IntegerField(blank=True, null=True)),
                ('septic_tank_size', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'form_detail',
            },
        ),
        migrations.AddField(
            model_name='documentmaster',
            name='isActive',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='documentmaster',
            name='mandatory',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='CitizenDocument',
        ),
        migrations.AddField(
            model_name='citizendocumentfilepath',
            name='document',
            field=models.ForeignKey(blank=True, db_column='doc_id_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citizen_documents_f', to='Masters.documentmaster'),
        ),
    ]
