# Generated by Django 4.2.7 on 2024-11-12 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0023_alter_citizen_document_tc_application_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application_form_tc',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_form_Ftc', to='Masters.status_master'),
        ),
    ]
