# Generated by Django 4.2.7 on 2024-11-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0024_alter_application_form_tc_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow_details',
            name='form_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
