# Generated by Django 4.2.7 on 2024-11-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0025_alter_workflow_details_form_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow_history',
            name='form_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
