# Generated by Django 4.2.7 on 2024-11-13 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Masters', '0026_alter_workflow_history_form_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='workflow_details_tc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request_no', models.TextField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('form_id', models.TextField(blank=True, null=True)),
                ('send_forward', models.TextField(blank=True, null=True)),
                ('forward', models.TextField(blank=True, null=True)),
                ('sendback', models.TextField(blank=True, null=True)),
                ('rollback', models.TextField(blank=True, null=True)),
                ('pre_statusid', models.TextField(blank=True, null=True)),
                ('pre_user', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
                ('form_user', models.ForeignKey(blank=True, db_column='form_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_flow_F_tc', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_flow_F_tc', to='Masters.status_master')),
            ],
            options={
                'db_table': 'workflow_details_tc',
            },
        ),
    ]
