# Generated by Django 4.2.7 on 2024-11-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0027_workflow_details_tc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service_master',
            old_name='redirect_to_service',
            new_name='citizen_page',
        ),
        migrations.AddField(
            model_name='service_master',
            name='internal_page',
            field=models.TextField(blank=True, null=True),
        ),
    ]
