# Generated by Django 4.2.7 on 2024-11-14 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0028_rename_redirect_to_service_service_master_citizen_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow_details',
            name='form_id',
            field=models.ForeignKey(blank=True, db_column='form_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_id_F', to='Masters.application_form'),
        ),
        migrations.AlterField(
            model_name='workflow_history',
            name='form_id',
            field=models.ForeignKey(blank=True, db_column='form_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hist_form_id_F', to='Masters.application_form'),
        ),
    ]
