# Generated by Django 4.2.7 on 2024-11-24 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TreeCutting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='internal_doc_master',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_name', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'internal_doc_master',
            },
        ),
        migrations.AddField(
            model_name='internal_user_document',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
