# Generated by Django 4.2.7 on 2024-11-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TreeCutting', '0002_internal_doc_master_internal_user_document_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='application_form',
            name='committee_approval',
            field=models.TextField(blank=True, null=True),
        ),
    ]
