# Generated by Django 4.2.7 on 2024-11-24 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrainageConnection', '0002_internal_doc_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='internal_user_document',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
