# Generated by Django 4.2.7 on 2025-05-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrainageConnection', '0003_internal_user_document_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='application_form',
            name='applicant_contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='application_form',
            name='declaration',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application_form',
            name='no_of_floors',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
