# Generated by Django 4.2.7 on 2025-01-30 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0006_document_master_doc_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ContractRegistration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application_form',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_form_cr', to='Masters.status_master'),
        ),
        migrations.AlterField(
            model_name='citizen_document',
            name='application_id',
            field=models.ForeignKey(blank=True, db_column='application_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_id_cr', to='ContractRegistration.application_form'),
        ),
        migrations.AlterField(
            model_name='citizen_document',
            name='document',
            field=models.ForeignKey(blank=True, db_column='doc_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citizen_documents_cr', to='Masters.document_master'),
        ),
        migrations.AlterField(
            model_name='internal_user_comments',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_intcom_cr', to='ContractRegistration.workflow_details'),
        ),
        migrations.AlterField(
            model_name='internal_user_document',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_intdoc_cr', to='ContractRegistration.workflow_details'),
        ),
        migrations.AlterField(
            model_name='workflow_details',
            name='form_id',
            field=models.ForeignKey(blank=True, db_column='form_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_id_cr', to='ContractRegistration.application_form'),
        ),
        migrations.AlterField(
            model_name='workflow_details',
            name='form_user',
            field=models.ForeignKey(blank=True, db_column='form_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_flow_cr', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workflow_details',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_flow_cr', to='Masters.status_master'),
        ),
        migrations.AlterField(
            model_name='workflow_history',
            name='form_id',
            field=models.ForeignKey(blank=True, db_column='form_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hist_form_id_cr', to='ContractRegistration.application_form'),
        ),
        migrations.AlterField(
            model_name='workflow_history',
            name='form_user',
            field=models.ForeignKey(blank=True, db_column='form_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_hist_cr', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workflow_history',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_hist_cr', to='Masters.status_master'),
        ),
    ]
