"""
Django settings for CSH project.TEST
Generated by 'django-admin startproject' using Django 4.2.6.
"""

from pathlib import Path
import os
from datetime import timedelta
from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ==================== SECURITY WARNING ====================
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$vute#e^tqlu5ehd!)vv5m3x!z5^7p%jb9hm9272-!6%0ouz*r'
SECRET_KEY1 = '5pQsZXhU8vKyv7GxThldGn_JLK9UXVYyZD3GwQxsztY='

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True  # Set to True for debugging, then change to False for production
DEBUG = False  # For production

# ==================== APPLICATION DEFINITION ====================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'axes',
    'corsheaders',
    'Account',
    'MenuManager',
    'Masters',
    'Reports',
    'Dashboard',
    'DrainageConnection',
    'TreeCutting',
    'TreeTrimming',
    'ContractRegistration',
    'ProductApproval',
]

# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'corsheaders.middleware.CorsMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'axes.middleware.AxesMiddleware',
#     'middleware.session_security.SessionExpiryRedirectMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'middleware.no_cache.NoCacheMiddleware',
#     'middleware.auth_flow.OTPBackForwardGuardMiddleware',
#     'middleware.auth_flow.DisableBrowserCacheMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
#     'django_auto_logout.middleware.auto_logout',
#     'Account.middleware.ServiceDatabaseMiddleware',
# ]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',

    # 🔐 brute-force protection
    'axes.middleware.AxesMiddleware',

    # 🔐 your custom controls that do NOT use messages
    'middleware.auth_flow.OTPBackForwardGuardMiddleware',
    'middleware.auth_flow.DisableBrowserCacheMiddleware',
    'middleware.session_security.SessionExpiryRedirectMiddleware',

    # ✅ Messages middleware must be before any middleware that uses messages
    'django.contrib.messages.middleware.MessageMiddleware',

    # 🔐 SESSION HIJACK PROTECTION (can now use messages safely)
    'middleware.session_binding.SessionBindingMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_auto_logout.middleware.auto_logout',
    'Account.middleware.ServiceDatabaseMiddleware',
]


ROOT_URLCONF = 'CSH.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        "DIRS": ['Template'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django_auto_logout.context_processors.auto_logout_client',
                'Account.context_processors.logged_in_user',
            ],
        },
    },
]

WSGI_APPLICATION = 'CSH.wsgi.application'

# ==================== DATABASE CONFIGURATION ====================
DATABASE_ROUTERS = ['Account.routers.ServiceRouter']

DATABASES = {
    'default': {
        'ENGINE': 'mysql.connector.django',
        'NAME': 'common_db1',
        'USER': 'root',
        'PASSWORD': 'Techno-cidco_MH-047319',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    },
    '1': {
        'ENGINE': 'mysql.connector.django',
        'NAME': 'drainage_connection_db1',
        'USER': 'root',
        'PASSWORD': 'Techno-cidco_MH-047319',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    },
    '2': {
        'ENGINE': 'mysql.connector.django',
        'NAME': 'tree_cutting_db1',
        'USER': 'root',
        'PASSWORD': 'Techno-cidco_MH-047319',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    },
    '3': {
        'ENGINE': 'mysql.connector.django',
        'NAME': 'tree_trimming_db1',
        'USER': 'root',
        'PASSWORD': 'Techno-cidco_MH-047319',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    },
    '4': {
        'ENGINE': 'mysql.connector.django',
        'NAME': 'contract_registration_db',
        'USER': 'root',
        'PASSWORD': 'Techno-cidco_MH-047319',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    },
    '5': {
        'ENGINE': 'mysql.connector.django',
        'NAME': 'product_approval_db',
        'USER': 'root',
        'PASSWORD': 'Techno-cidco_MH-047319',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    },
}

# ==================== ALLOWED HOSTS (CRITICAL) ====================
# For debugging, allow all hosts temporarily
ALLOWED_HOSTS = [
    '13.126.65.190',
    '172.16.20.48',
    '3.7.229.137',
    'rtsengser.cidcoindia.com',
    'localhost',
    '127.0.0.1'
]

# ==================== CORS SETTINGS ====================
CORS_ALLOWED_ORIGINS = [
    'http://13.202.157.7',
    'https://push3.aclgateway.com',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://localhost',
    'http://127.0.0.1',
]

CORS_ORIGIN_ALLOW_ALL = False

# ==================== CSRF SETTINGS ====================
# For Django 4.0+, CSRF_TRUSTED_ORIGINS must include scheme
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://localhost',
    'http://127.0.0.1',
    'http://13.202.157.7',
    'http://push3.aclgateway.com',
    'http://3.7.229.137',
    'http://rtsengser.cidcoindia.com',
    'http://localhost',
    'http://127.0.0.1',
]

# ==================== SECURITY SETTINGS ====================
# Disable security features in debug mode
if DEBUG:
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False
else:
    # You have NO SSL, so still keep these False
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False


# ==================== SESSION & AUTHENTICATION ====================
SESSION_EXPIRE_AFTER_LAST_ACTIVITY = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 3600
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'

CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_USE_SESSIONS = False

AUTH_USER_MODEL = 'Account.CustomUser'

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Account Lockout
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1
AXES_ENABLED = not DEBUG  # Disable in debug mode

# Login/Logout URLs
LOGIN_URL = "Account"
LOGIN_REDIRECT_URL = 'Account'
LOGOUT_REDIRECT_URL = 'Account'

AUTO_LOGOUT = {
    'IDLE_TIME': 3600,
    'REDIRECT_TO_LOGIN_IMMEDIATELY': True,
    'MESSAGE': 'The session has expired. Please login again to continue.',
}

USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'http')

# ==================== SECURITY HEADERS ====================
X_FRAME_OPTIONS = 'DENY'
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# ==================== PASSWORD VALIDATION ====================
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ==================== INTERNATIONALIZATION ====================
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_TZ = True

# ==================== STATIC & MEDIA FILES ====================
STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

MEDIA_URL = '/media/'
if DEBUG:
    MEDIA_ROOT = os.path.join(BASE_DIR, 'D:/Python Project/Documents/')
else:
    MEDIA_ROOT = os.path.join(BASE_DIR, '/home/ubuntu/Documents/')
    # MEDIA_ROOT = os.path.join(BASE_DIR, '/home/services/Documents/')

# ==================== EMAIL CONFIGURATION ====================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'noreply.Complianceoperation@gmail.com'
EMAIL_HOST_PASSWORD = 'mgypdsldfzsvyvle'

# ==================== OTHER SETTINGS ====================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
ENCRYPTION_KEY = os.environ.get('ENCRYPTION_KEY', 'oRVCHTumzesh-E71A-bAnjjEDuIlkceL6dvAYiCShp0=')

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=2),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': False,
}

CELERY_BEAT_SCHEDULE = {
    'notify_users_2pm': {
        'task': 'your_app.tasks.check_and_notify_all_users',
        'schedule': crontab(hour=14, minute=0),
    },
    'notify_users_7pm': {
        'task': 'your_app.tasks.check_and_notify_all_users',
        'schedule': crontab(hour=19, minute=0),
    },
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            # 'filename': os.path.join(BASE_DIR, 'D:/Python Project/CSH Logs', 'django.log'),  
            'filename': os.path.join(BASE_DIR, '/home/ubuntu/CSH Logs', 'django.log'),  
            # 'filename': os.path.join(BASE_DIR, '/home/services/CSH Logs', 'django.log'),  
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'WARNING',
            'propagate': True,
        },
    },
}