# Generated by Django 4.2.7 on 2024-11-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuMaster',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_name', models.CharField(blank=True, max_length=50, null=True)),
                ('menu_action', models.CharField(blank=True, max_length=50, null=True)),
                ('menu_is_parent', models.BooleanField(blank=True, null=True)),
                ('menu_parent_id', models.IntegerField(blank=True, null=True)),
                ('menu_order', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('is_sub_menu', models.BooleanField(blank=True, null=True)),
                ('sub_menu', models.IntegerField(blank=True, null=True)),
                ('is_sub_menu2', models.BooleanField(blank=True, null=True)),
                ('sub_menu2', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
                ('menu_icon', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'menu_master',
            },
        ),
        migrations.CreateModel(
            name='RoleMenuMaster',
            fields=[
                ('role_menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_id', models.CharField(blank=True, max_length=50, null=True)),
                ('menu_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'role_menu_master',
            },
        ),
        migrations.CreateModel(
            name='UserMenuDetails',
            fields=[
                ('user_menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('menu_id', models.IntegerField(blank=True, null=True)),
                ('role_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_menu_details',
            },
        ),
    ]
